### ISSUE TITLE
Project Outline Feedback

### ISSUE THREAD

**Issue by dan-hart** [polishponcho/liftoff-assignments#1]
**Features Section:** Overall these look great. Going into the project it will help to be specific about what data points will be tracked in the "Create and Edit Data Points" section. Would that just be number of elopements? Or some other type of data? I have similar feedback about the graphs, what types of graphs will be provided? How many? 

**Technologies & Learning Section:** Which track did you participate in LC 101? Did your Cheese MVC app use a python log in? If you have not done graphs or mailing APIs it may be best to pick on or the other to start (to focus your MVP), and leave one as a stretch goal (backlog).

Overall this looks great and the project solves a real problem!

**Comment by dan-hart** [comment]
@polishponcho Also, please add a link to your project tracker to your outline. Thanks!

**Comment by polishponcho** [comment]
Updated my project outline, and hopefully that clears things up a bit.  I took the C# track but Cheese MVC did not have a log in feature.  We did login features with python in Unit 2 of LC101.
