### ISSUE TITLE
Project Planning Feedback

### ISSUE THREAD

**Issue by dan-hart** [polishponcho/liftoff-assignments#2]
Ryan, the wireframes look good. To provide useful user stories on your pivotal tracker, all user stories should be in this format: [define user][define action][justification]. "As a logged in user, I can create a new expense, so that I can track all of my expenses."

Try to break out the stories in to smaller sections, each being a specific [user][action[justification] combination.

**Comment by polishponcho** [comment]
Thank you Dan!
I have rewrote my user stories to fulfill the proper format!
Check them out!
https://www.pivotaltracker.com/n/projects/2238524

**Comment by dan-hart** [comment]
Fantastic!
